kind: Service
metadata:
  name: nginx-service #The name of the Kubernetes Service to be created in the Kubernetes cluster
spec:
  selector:
    app: nginx-deployment 
  type: NodePort #Type of the Kubernetes Service
  ports:
  - protocol: TCP
    port: 80 #Service port
    targetPort: 80 #The port for the application container
